global using AutoMapper;
// Application Dependencies
global using Eventify.Application.Handlers.Commands;
global using Eventify.Application.Interfaces.Commands;
global using Eventify.Application.Interfaces.Handlers;
// Domain Dependencies
global using Eventify.Domain.Entities;
global using Eventify.Domain.IRepositories;
global using Eventify.Domain.ValueObjects;
// Infrastructure Dependencies
global using Eventify.Infrastructure.EFRepositories;
global using Eventify.IntegrationTests.Config;
// Test Dependencies
global using Eventify.IntegrationTests.Config.Fixtures;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Xunit;
